### ISSUE TITLE
How to send CTRL-ALT-DEL?

### ISSUE THREAD

**Issue by gvgit** [npat-efault/picocom#99]
I can't reset my machine via picocom. If I enter `CTRL-ALT-DEL` my local machine is restarted, not my remote machine. Is there a way to reset the remote machine? Can't find anythink in the docs.

I tried `picocom --omap delbs -b 9600 /dev/ttyUSB0` but no remote reaction.

**Comment by npat-efault** [comment]
The short answer is: No there isn't.

Sending "CTRL-ALT-DEL" make no sense: What byte or  bytes would picocom send? These are modifier keys that do not correspond to bytes / characters, so they cannot be send down a serial connection.

The only possible way to program (or modify) your shell / login application (at the remote end), so that it resets the system when it sees a certain sequence of bytes on the serial port.
